### ISSUE TITLE
Setup the private Hyperledger blockchain node for testing purposes

### ISSUE THREAD

**Issue by mykola-digtiar** [TU-ADSP/Blockchain-Logging-Framework#2]
1. Create a tutorial of how to access the blockchain node i.e. host and port and so on...
2. Setup (web-)clients and create a tutorial of how one could send a transaction/smart-contract onto the chain

**Comment by rohrschacht** [comment]
We set up the Hyperledger test network on the VM. I wrote a small explanation on how to access it [here in the wiki](https://github.com/TU-ADSP/Blockchain-Logging-Framework/wiki/Interacting-with-Hyperledger).
I think the second part in the description:
```
2. Setup (web-)clients and create a tutorial of how one could send a transaction/smart-contract onto the chain
```
actually better belongs to the issue #34 of deploying chain code to this network.
So I am going ahead and calling this closed now, you can reopen it if you think otherwise :)
