### ISSUE TITLE
Deploy chain-code onto the Hyperledger blockchain for testing purposes

### ISSUE THREAD

**Issue by mykola-digtiar** [TU-ADSP/Blockchain-Logging-Framework#34]

**Comment by rohrschacht** [comment]
Alright, so I followed [this tutorial from the official hyperledger documentation](https://hyperledger-fabric.readthedocs.io/en/release-2.2/test_network.html) and after some hiccups, I got the `basic-asset-transfer` chain code to run on the local Hyperledger test network we set up.

In order to interact with the network and the blockchain itself, some setting up of the shell is needed, which I think can be fully automated. I will try to write a script for that and document that in our wiki, so that all of you can easily interact with the blockchain. I'd consider this issue closed when I am done with this. However, maybe we should talk about and clarify if we actually want to write some chain code with some business logic of our own, or if this example chain code is enough for the start.

Here is the example output that shows that the example chain code is deployed and the assets are on the chain:
```
$ peer chaincode query -C mychannel -n basic -c '{"Args":["GetAllAssets"]}' | jq
[
  {
    "ID": "asset1",
    "color": "blue",
    "size": 5,
    "owner": "Tomoko",
    "appraisedValue": 300
  },
  {
    "ID": "asset2",
    "color": "red",
    "size": 5,
    "owner": "Brad",
    "appraisedValue": 400
  },
  {
    "ID": "asset3",
    "color": "green",
    "size": 10,
    "owner": "Jin Soo",
    "appraisedValue": 500
  },
  {
    "ID": "asset4",
    "color": "yellow",
    "size": 10,
    "owner": "Max",
    "appraisedValue": 600
  },
  {
    "ID": "asset5",
    "color": "black",
    "size": 15,
    "owner": "Adriana",
    "appraisedValue": 700
  },
  {
    "ID": "asset6",
    "color": "white",
    "size": 15,
    "owner": "Michel",
    "appraisedValue": 800
  }
]
```

**Comment by hb237** [comment]
Good!

**Comment by rohrschacht** [comment]
I automated the shell environment setup needed to interact with the chain code. I also implemented a small shell that can be used as client to interact even more easily with the deployed example chain code. I documented both [on the wiki](https://github.com/TU-ADSP/Blockchain-Logging-Framework/wiki/Interacting-with-Hyperledger).

Now the issue is closed ;)
